version: '3'

services:
  web1:
    image: app1:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      - app_net
  web2:
    image: app2:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      - app_net
  nginx:
    image: nginx:latest
    ports:
      - "1111:1111"
      - "1112:1112"
    depends_on:
      - web1
      - web2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_net

networks:
  app_net:
